// Copyright 2022 Stichting ThingsIX Foundation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.4
// source: mapper/mapper.proto

package mapper

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DiscoveryPacketReceipt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Frequency        uint32                 `protobuf:"varint,1,opt,name=frequency,proto3" json:"frequency,omitempty"`
	Rssi             int32                  `protobuf:"varint,2,opt,name=rssi,proto3" json:"rssi,omitempty"`
	LoraSnr          float64                `protobuf:"fixed64,3,opt,name=loraSnr,proto3" json:"loraSnr,omitempty"`
	SpreadingFactor  uint32                 `protobuf:"varint,4,opt,name=spreadingFactor,proto3" json:"spreadingFactor,omitempty"`
	Bandwidth        uint32                 `protobuf:"varint,5,opt,name=bandwidth,proto3" json:"bandwidth,omitempty"`
	CodeRate         string                 `protobuf:"bytes,6,opt,name=codeRate,proto3" json:"codeRate,omitempty"`
	Phy              []byte                 `protobuf:"bytes,7,opt,name=phy,proto3" json:"phy,omitempty"`
	Time             *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=time,proto3" json:"time,omitempty"`
	GatewaySignature []byte                 `protobuf:"bytes,9,opt,name=gatewaySignature,proto3" json:"gatewaySignature,omitempty"`
}

func (x *DiscoveryPacketReceipt) Reset() {
	*x = DiscoveryPacketReceipt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapper_mapper_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiscoveryPacketReceipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryPacketReceipt) ProtoMessage() {}

func (x *DiscoveryPacketReceipt) ProtoReflect() protoreflect.Message {
	mi := &file_mapper_mapper_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryPacketReceipt.ProtoReflect.Descriptor instead.
func (*DiscoveryPacketReceipt) Descriptor() ([]byte, []int) {
	return file_mapper_mapper_proto_rawDescGZIP(), []int{0}
}

func (x *DiscoveryPacketReceipt) GetFrequency() uint32 {
	if x != nil {
		return x.Frequency
	}
	return 0
}

func (x *DiscoveryPacketReceipt) GetRssi() int32 {
	if x != nil {
		return x.Rssi
	}
	return 0
}

func (x *DiscoveryPacketReceipt) GetLoraSnr() float64 {
	if x != nil {
		return x.LoraSnr
	}
	return 0
}

func (x *DiscoveryPacketReceipt) GetSpreadingFactor() uint32 {
	if x != nil {
		return x.SpreadingFactor
	}
	return 0
}

func (x *DiscoveryPacketReceipt) GetBandwidth() uint32 {
	if x != nil {
		return x.Bandwidth
	}
	return 0
}

func (x *DiscoveryPacketReceipt) GetCodeRate() string {
	if x != nil {
		return x.CodeRate
	}
	return ""
}

func (x *DiscoveryPacketReceipt) GetPhy() []byte {
	if x != nil {
		return x.Phy
	}
	return nil
}

func (x *DiscoveryPacketReceipt) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *DiscoveryPacketReceipt) GetGatewaySignature() []byte {
	if x != nil {
		return x.GatewaySignature
	}
	return nil
}

type DownlinkConfirmationPacketReceipt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Frequency        uint32                 `protobuf:"varint,1,opt,name=frequency,proto3" json:"frequency,omitempty"`
	Rssi             int32                  `protobuf:"varint,2,opt,name=rssi,proto3" json:"rssi,omitempty"`
	LoraSnr          float64                `protobuf:"fixed64,3,opt,name=loraSnr,proto3" json:"loraSnr,omitempty"`
	SpreadingFactor  uint32                 `protobuf:"varint,4,opt,name=spreadingFactor,proto3" json:"spreadingFactor,omitempty"`
	Bandwidth        uint32                 `protobuf:"varint,5,opt,name=bandwidth,proto3" json:"bandwidth,omitempty"`
	CodeRate         string                 `protobuf:"bytes,6,opt,name=codeRate,proto3" json:"codeRate,omitempty"`
	Phy              []byte                 `protobuf:"bytes,7,opt,name=phy,proto3" json:"phy,omitempty"`
	Time             *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=time,proto3" json:"time,omitempty"`
	GatewaySignature []byte                 `protobuf:"bytes,9,opt,name=gatewaySignature,proto3" json:"gatewaySignature,omitempty"`
}

func (x *DownlinkConfirmationPacketReceipt) Reset() {
	*x = DownlinkConfirmationPacketReceipt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapper_mapper_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownlinkConfirmationPacketReceipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownlinkConfirmationPacketReceipt) ProtoMessage() {}

func (x *DownlinkConfirmationPacketReceipt) ProtoReflect() protoreflect.Message {
	mi := &file_mapper_mapper_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownlinkConfirmationPacketReceipt.ProtoReflect.Descriptor instead.
func (*DownlinkConfirmationPacketReceipt) Descriptor() ([]byte, []int) {
	return file_mapper_mapper_proto_rawDescGZIP(), []int{1}
}

func (x *DownlinkConfirmationPacketReceipt) GetFrequency() uint32 {
	if x != nil {
		return x.Frequency
	}
	return 0
}

func (x *DownlinkConfirmationPacketReceipt) GetRssi() int32 {
	if x != nil {
		return x.Rssi
	}
	return 0
}

func (x *DownlinkConfirmationPacketReceipt) GetLoraSnr() float64 {
	if x != nil {
		return x.LoraSnr
	}
	return 0
}

func (x *DownlinkConfirmationPacketReceipt) GetSpreadingFactor() uint32 {
	if x != nil {
		return x.SpreadingFactor
	}
	return 0
}

func (x *DownlinkConfirmationPacketReceipt) GetBandwidth() uint32 {
	if x != nil {
		return x.Bandwidth
	}
	return 0
}

func (x *DownlinkConfirmationPacketReceipt) GetCodeRate() string {
	if x != nil {
		return x.CodeRate
	}
	return ""
}

func (x *DownlinkConfirmationPacketReceipt) GetPhy() []byte {
	if x != nil {
		return x.Phy
	}
	return nil
}

func (x *DownlinkConfirmationPacketReceipt) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *DownlinkConfirmationPacketReceipt) GetGatewaySignature() []byte {
	if x != nil {
		return x.GatewaySignature
	}
	return nil
}

type DownlinkTransmitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Frequency       uint32 `protobuf:"varint,1,opt,name=frequency,proto3" json:"frequency,omitempty"`
	Power           int32  `protobuf:"varint,2,opt,name=power,proto3" json:"power,omitempty"` // in dBm EIRP
	SpreadingFactor uint32 `protobuf:"varint,3,opt,name=spreadingFactor,proto3" json:"spreadingFactor,omitempty"`
	Bandwidth       uint32 `protobuf:"varint,4,opt,name=bandwidth,proto3" json:"bandwidth,omitempty"`
	CodeRate        string `protobuf:"bytes,5,opt,name=codeRate,proto3" json:"codeRate,omitempty"`
	Phy             []byte `protobuf:"bytes,6,opt,name=phy,proto3" json:"phy,omitempty"`
}

func (x *DownlinkTransmitRequest) Reset() {
	*x = DownlinkTransmitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapper_mapper_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownlinkTransmitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownlinkTransmitRequest) ProtoMessage() {}

func (x *DownlinkTransmitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mapper_mapper_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownlinkTransmitRequest.ProtoReflect.Descriptor instead.
func (*DownlinkTransmitRequest) Descriptor() ([]byte, []int) {
	return file_mapper_mapper_proto_rawDescGZIP(), []int{2}
}

func (x *DownlinkTransmitRequest) GetFrequency() uint32 {
	if x != nil {
		return x.Frequency
	}
	return 0
}

func (x *DownlinkTransmitRequest) GetPower() int32 {
	if x != nil {
		return x.Power
	}
	return 0
}

func (x *DownlinkTransmitRequest) GetSpreadingFactor() uint32 {
	if x != nil {
		return x.SpreadingFactor
	}
	return 0
}

func (x *DownlinkTransmitRequest) GetBandwidth() uint32 {
	if x != nil {
		return x.Bandwidth
	}
	return 0
}

func (x *DownlinkTransmitRequest) GetCodeRate() string {
	if x != nil {
		return x.CodeRate
	}
	return ""
}

func (x *DownlinkTransmitRequest) GetPhy() []byte {
	if x != nil {
		return x.Phy
	}
	return nil
}

type DiscoveryPacketReceiptResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//
	//	*DiscoveryPacketReceiptResponse_DownlinkTransmitRequest
	//	*DiscoveryPacketReceiptResponse_Empty
	Response isDiscoveryPacketReceiptResponse_Response `protobuf_oneof:"response"`
}

func (x *DiscoveryPacketReceiptResponse) Reset() {
	*x = DiscoveryPacketReceiptResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mapper_mapper_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiscoveryPacketReceiptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryPacketReceiptResponse) ProtoMessage() {}

func (x *DiscoveryPacketReceiptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mapper_mapper_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryPacketReceiptResponse.ProtoReflect.Descriptor instead.
func (*DiscoveryPacketReceiptResponse) Descriptor() ([]byte, []int) {
	return file_mapper_mapper_proto_rawDescGZIP(), []int{3}
}

func (m *DiscoveryPacketReceiptResponse) GetResponse() isDiscoveryPacketReceiptResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *DiscoveryPacketReceiptResponse) GetDownlinkTransmitRequest() *DownlinkTransmitRequest {
	if x, ok := x.GetResponse().(*DiscoveryPacketReceiptResponse_DownlinkTransmitRequest); ok {
		return x.DownlinkTransmitRequest
	}
	return nil
}

func (x *DiscoveryPacketReceiptResponse) GetEmpty() *emptypb.Empty {
	if x, ok := x.GetResponse().(*DiscoveryPacketReceiptResponse_Empty); ok {
		return x.Empty
	}
	return nil
}

type isDiscoveryPacketReceiptResponse_Response interface {
	isDiscoveryPacketReceiptResponse_Response()
}

type DiscoveryPacketReceiptResponse_DownlinkTransmitRequest struct {
	DownlinkTransmitRequest *DownlinkTransmitRequest `protobuf:"bytes,1,opt,name=downlinkTransmitRequest,proto3,oneof"`
}

type DiscoveryPacketReceiptResponse_Empty struct {
	Empty *emptypb.Empty `protobuf:"bytes,2,opt,name=empty,proto3,oneof"`
}

func (*DiscoveryPacketReceiptResponse_DownlinkTransmitRequest) isDiscoveryPacketReceiptResponse_Response() {
}

func (*DiscoveryPacketReceiptResponse_Empty) isDiscoveryPacketReceiptResponse_Response() {}

var File_mapper_mapper_proto protoreflect.FileDescriptor

var file_mapper_mapper_proto_rawDesc = []byte{
	0x0a, 0x13, 0x6d, 0x61, 0x70, 0x70, 0x65, 0x72, 0x2f, 0x6d, 0x61, 0x70, 0x70, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6d, 0x61, 0x70, 0x70, 0x65, 0x72, 0x1a, 0x1f, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb6, 0x02, 0x0a, 0x16,
	0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x52,
	0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x6e, 0x63, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x66, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x6e, 0x63, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x73, 0x73, 0x69, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x72, 0x73, 0x73, 0x69, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x6f, 0x72, 0x61,
	0x53, 0x6e, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x6c, 0x6f, 0x72, 0x61, 0x53,
	0x6e, 0x72, 0x12, 0x28, 0x0a, 0x0f, 0x73, 0x70, 0x72, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x46,
	0x61, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0f, 0x73, 0x70, 0x72,
	0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x46, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x1c, 0x0a, 0x09,
	0x62, 0x61, 0x6e, 0x64, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x09, 0x62, 0x61, 0x6e, 0x64, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f,
	0x64, 0x65, 0x52, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6f,
	0x64, 0x65, 0x52, 0x61, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x68, 0x79, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x03, 0x70, 0x68, 0x79, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x10, 0x67, 0x61, 0x74, 0x65,
	0x77, 0x61, 0x79, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x10, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x53, 0x69, 0x67, 0x6e, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x22, 0xc1, 0x02, 0x0a, 0x21, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x69, 0x6e,
	0x6b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x63,
	0x6b, 0x65, 0x74, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x66,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x73, 0x73, 0x69,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x72, 0x73, 0x73, 0x69, 0x12, 0x18, 0x0a, 0x07,
	0x6c, 0x6f, 0x72, 0x61, 0x53, 0x6e, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x6c,
	0x6f, 0x72, 0x61, 0x53, 0x6e, 0x72, 0x12, 0x28, 0x0a, 0x0f, 0x73, 0x70, 0x72, 0x65, 0x61, 0x64,
	0x69, 0x6e, 0x67, 0x46, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x0f, 0x73, 0x70, 0x72, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x46, 0x61, 0x63, 0x74, 0x6f, 0x72,
	0x12, 0x1c, 0x0a, 0x09, 0x62, 0x61, 0x6e, 0x64, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x09, 0x62, 0x61, 0x6e, 0x64, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x1a,
	0x0a, 0x08, 0x63, 0x6f, 0x64, 0x65, 0x52, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x63, 0x6f, 0x64, 0x65, 0x52, 0x61, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x68,
	0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x70, 0x68, 0x79, 0x12, 0x2e, 0x0a, 0x04,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x10,
	0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x10, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x53,
	0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0xc3, 0x01, 0x0a, 0x17, 0x44, 0x6f, 0x77,
	0x6e, 0x6c, 0x69, 0x6e, 0x6b, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x72, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x66, 0x72, 0x65, 0x71, 0x75, 0x65, 0x6e,
	0x63, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x12, 0x28, 0x0a, 0x0f, 0x73, 0x70, 0x72, 0x65,
	0x61, 0x64, 0x69, 0x6e, 0x67, 0x46, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0f, 0x73, 0x70, 0x72, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x46, 0x61, 0x63, 0x74,
	0x6f, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x61, 0x6e, 0x64, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x62, 0x61, 0x6e, 0x64, 0x77, 0x69, 0x64, 0x74, 0x68,
	0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x64, 0x65, 0x52, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x63, 0x6f, 0x64, 0x65, 0x52, 0x61, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x70, 0x68, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x70, 0x68, 0x79, 0x22, 0xb9,
	0x01, 0x0a, 0x1e, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x50, 0x61, 0x63, 0x6b,
	0x65, 0x74, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x5b, 0x0a, 0x17, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x69, 0x6e, 0x6b, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6d, 0x61, 0x70, 0x70, 0x65, 0x72, 0x2e, 0x44, 0x6f, 0x77, 0x6e,
	0x6c, 0x69, 0x6e, 0x6b, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x17, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x69, 0x6e, 0x6b, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e,
	0x0a, 0x05, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x48, 0x00, 0x52, 0x05, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x0a,
	0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x54, 0x68, 0x69, 0x6e, 0x67, 0x73, 0x49,
	0x58, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x63, 0x6f, 0x76, 0x65,
	0x72, 0x61, 0x67, 0x65, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x6f, 0x2f, 0x6d, 0x61, 0x70, 0x70,
	0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mapper_mapper_proto_rawDescOnce sync.Once
	file_mapper_mapper_proto_rawDescData = file_mapper_mapper_proto_rawDesc
)

func file_mapper_mapper_proto_rawDescGZIP() []byte {
	file_mapper_mapper_proto_rawDescOnce.Do(func() {
		file_mapper_mapper_proto_rawDescData = protoimpl.X.CompressGZIP(file_mapper_mapper_proto_rawDescData)
	})
	return file_mapper_mapper_proto_rawDescData
}

var file_mapper_mapper_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_mapper_mapper_proto_goTypes = []interface{}{
	(*DiscoveryPacketReceipt)(nil),            // 0: mapper.DiscoveryPacketReceipt
	(*DownlinkConfirmationPacketReceipt)(nil), // 1: mapper.DownlinkConfirmationPacketReceipt
	(*DownlinkTransmitRequest)(nil),           // 2: mapper.DownlinkTransmitRequest
	(*DiscoveryPacketReceiptResponse)(nil),    // 3: mapper.DiscoveryPacketReceiptResponse
	(*timestamppb.Timestamp)(nil),             // 4: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                     // 5: google.protobuf.Empty
}
var file_mapper_mapper_proto_depIdxs = []int32{
	4, // 0: mapper.DiscoveryPacketReceipt.time:type_name -> google.protobuf.Timestamp
	4, // 1: mapper.DownlinkConfirmationPacketReceipt.time:type_name -> google.protobuf.Timestamp
	2, // 2: mapper.DiscoveryPacketReceiptResponse.downlinkTransmitRequest:type_name -> mapper.DownlinkTransmitRequest
	5, // 3: mapper.DiscoveryPacketReceiptResponse.empty:type_name -> google.protobuf.Empty
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_mapper_mapper_proto_init() }
func file_mapper_mapper_proto_init() {
	if File_mapper_mapper_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mapper_mapper_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiscoveryPacketReceipt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapper_mapper_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownlinkConfirmationPacketReceipt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapper_mapper_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownlinkTransmitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mapper_mapper_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiscoveryPacketReceiptResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_mapper_mapper_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*DiscoveryPacketReceiptResponse_DownlinkTransmitRequest)(nil),
		(*DiscoveryPacketReceiptResponse_Empty)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mapper_mapper_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mapper_mapper_proto_goTypes,
		DependencyIndexes: file_mapper_mapper_proto_depIdxs,
		MessageInfos:      file_mapper_mapper_proto_msgTypes,
	}.Build()
	File_mapper_mapper_proto = out.File
	file_mapper_mapper_proto_rawDesc = nil
	file_mapper_mapper_proto_goTypes = nil
	file_mapper_mapper_proto_depIdxs = nil
}
